- name: Remove old ruby
  apt: name=ruby state=absent purge=yes

- name: Download chruby
  command: wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz chdir=/tmp

- name: Extract
  command: tar xzf chruby-0.3.9.tar.gz chdir=/tmp

- name: Install chruby
  command: sudo make install chdir=/tmp/chruby-0.3.9

- name: Configuring
  command: bash setup.sh chdir=/tmp/chruby-0.3.9/script

- name: Configuring
  lineinfile: dest=/etc/profile.d/chruby.sh insertafter="^fi " line="source /usr/local/share/chruby/chruby.sh"

- name: Install Dependencies from Ruby
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - g++
    - openssl
    - libtool
    - libc6-dev
    - libreadline6
    - libreadline6-dev
    - libncurses5-dev
    - ncurses-dev
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt-dev
    - libffi-dev
    - autoconf
    - automake
    - bison
    - pkg-config
    - sqlite3

- name: Download Ruby
  get_url: url=http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.5.tar.gz dest=/tmp mode=0440

- name: Extract Ruby
  command: tar xzf /tmp/ruby-2.1.5.tar.gz chdir=/tmp

- name: Build Ruby
  command: sudo {{ item }} chdir="/tmp/ruby-2.1.5"
  with_items:
    - ./configure --prefix=/opt/rubies/ruby-2.1.5
    - make
    - make install

- name: Install Bundler
  command: gem install bundler
