- name: Install rvm and ruby
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - g++
    - openssl
    - libtool
    - libc6-dev
    - libreadline6
    - libreadline6-dev
    - libncurses5-dev
    - ncurses-dev
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt-dev
    - libffi-dev
    - autoconf
    - automake
    - bison
    - pkg-config
    - sqlite3

– name: Install rvm gpg
  shell: >
    executable=/bin/bash
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

– name: Install RVM
  shell: curl -L get.rvm.io | bash -s stable

– name: Install Ruby 2.2.2
  shell: >
    executable=/bin/bash source /etc/profile.d/rvm.sh;
    rvm install 2.2.2

– name: Set default ruby version
  shell: >
    executable=/bin/bash source /etc/profile.d/rvm.sh;
    rvm —default use 2.2.2

- name: Install Bundler
  command: gem install bundler

- name: Add no docs gemrc
  template: src=gemrc.tpl dest='~/.gemrc'
