- name: Remove old ruby
  apt: name=ruby state=absent purge=yes

- name: Install Dependencies from Ruby
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - g++
    - openssl
    - libtool
    - libc6-dev
    - libreadline6
    - libreadline6-dev
    - libncurses5-dev
    - ncurses-dev
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt-dev
    - libffi-dev
    - autoconf
    - automake
    - bison
    - pkg-config
    - sqlite3
  tags: ruby

- name: Check if the Ruby zip exists.
  command: /usr/bin/test -e /tmp/ruby-2.1.5.tar.gz
  ignore_errors: True
  register: ruby_exists

- name: Download Ruby
  get_url: url=http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.5.tar.gz dest=/tmp mode=0440
  when: ruby_exists.rc != 0

- name: Extract Ruby
  command: sudo tar xzf /tmp/ruby-2.1.5.tar.gz chdir=/tmp

- name: Build Ruby
  command: sudo {{ item }} chdir="/tmp/ruby-2.1.5"
  with_items:
    - ./configure
    - make
    - make install