- name: Add no docs gemrc and use local gem instalation
  template: >
    src=gemrc.tpl dest=/home/{{ user }}/.gemrc
    owner={{ user }} group={{ user }} mode=0600
  tags:
    - ruby

- name: Insert local gem path to .bashrc
  lineinfile: >
    dest=/home/{{ user }}/.bashrc
    line="{{ item.line }}"
  with_items:
    - {line: '# set PATH for exec gems' }
    - {line: 'if which ruby >/dev/null && which gem >/dev/null; then' }
    - {line: "    PATH=\\\"$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH\\\"" }
    - {line: '\nfi' }
  tags:
    - ruby