---
- name: Update apt
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600

- name: hellobits key
  apt_key: url=http://apt.hellobits.com/hellobits.key

- name: Add hellobits repo
  apt_repository: >
    repo='deb [arch=amd64] http://apt.hellobits.com/ trusty main'
    state=present

- name: Install ruby
  apt: >
    pkg=ruby-2.2
    update_cache=yes
    cache_valid_time=3600
    state=latest
    force=yes

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties
    - git-core
    - nodejs
    - imagemagick
    - build-essential
    - autoconf
    - automake
    - bison
    - libc6-dev
    - libffi-dev
    - libreadline6
    - libreadline6-dev
    - libssl-dev
    - libtool
    - libxml2-dev
    - libxslt-dev
    - libxslt1-dev
    - libyaml-dev
    - ncurses-dev
    - zlib1g
    - zlib1g-dev
    - git

- name: Add user
  user: name={{ user }} shell=/bin/bash groups=www-data
  tags:
    - user

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone
  tags:
    - user

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes backup=yes
  tags:
    - user

- name: Set the hostname in /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined
  tags:
    - user

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined
  tags:
    - user

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644
  tags:
    - user