export PATH=/opt/chefdk/bin:/Users/rberger/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/embedded/bin:/opt/chefdk/bin:/Users/rberger/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/embedded/bin:/Users/rberger/anaconda/bin:/Users/rberger/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin:/usr/local/opt/go/libexec/bin
export GEM_ROOT="/opt/chefdk/embedded/lib/ruby/gems/2.1.0"
export GEM_HOME=/opt/chefdk/embedded/lib/ruby/gems/2.1.0
export GEM_PATH=/Users/rberger/.chefdk/gem/ruby/2.1.0:/opt/chefdk/embedded/lib/ruby/gems/2.

ncm bebedouro 84186931


export GEM_HOME="$HOME/.gems"
- name: Remove old ruby
  apt: name=ruby state=absent purge=yes

- name: Download chruby
  shell: wget -O chruby-{{ chruby_version }}.tar.gz https://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz
  when:
    ansible_local is not defined or
    ansible_local.chruby is not defined or
    ansible_local.chruby.version != chruby_version
  register: chruby_downloaded

- name: Extract chruby
  shell: tar -xzvf chruby-{{ chruby_version }}.tar.gz
  when: chruby_downloaded | changed
  register: chruby_extracted

- name: Install chruby
  sudo: true
  shell: cd chruby-{{ chruby_version }}/ && make install
  when: chruby_extracted | changed
  register: chruby_installed

- name: Clean up chruby sources
  shell: rm -rf chruby-*
  when: chruby_downloaded | changed

- name: Attach chruby into shell
  sudo: true
  template: src=default.tpl dest=/etc/profile.d/chruby.sh

#
# Setup chruby facts.d
#
- name: Capture installed chruby version
  shell: >
    executable=/bin/bash source /etc/profile;
    chruby --version | awk '{ print $2 }'
  ignore_errors: yes
  register: installed_chruby_version

- name: Create ansible facts directory
  sudo: true
  file: state=directory recurse=yes path=/etc/ansible/facts.d

- name: Set chruby facts
  sudo: true
  template: src=chruby.fact dest=/etc/ansible/facts.d/chruby.fact