---

- name: Add Keys for PostgreSQL Repository
  sudo: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Add PostgreSQL Repository
  sudo: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main' state=present

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install PostgreSQL Packages
  sudo: yes
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - postgresql
    - postgresql-client
    - python-pygresql
    - python-psycopg2
    - libpq-dev

- name: Create databases
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ pgsql.db_database }} state=present

- name: Create users
  sudo: yes
  sudo_user: postgres
  postgresql_user: >
    name={{ pgsql.db_user }}
    password={{ pgsql.db_password }}
    db={{ pgsql.db_database }}
    priv=ALL